#ifndef __SOFTGPU_VERSION_H__INCLUDED__

#define SOFTGPU_ICON1 101

#define SOFTGPU_STR_(x) #x
#define SOFTGPU_STR(x) SOFTGPU_STR_(x)

#define SOFTGPU_MAJOR 0
#define SOFTGPU_MINOR 6

#ifndef SOFTGPU_PATCH
#define SOFTGPU_PATCH 2024
#endif

#ifndef SOFTGPU_BUILD
#define SOFTGPU_BUILD 0
#endif

#define SOFTGPU_TAG "ALPHA3"

#define SOFTGPU_VERSION_STR_BUILD(_ma, _mi, _pa, _bl, _tag) \
	_ma "." _mi "." _pa "." _bl "-" _tag

#define SOFTGPU_VERSION_STR SOFTGPU_VERSION_STR_BUILD( \
	SOFTGPU_STR(SOFTGPU_MAJOR), \
	SOFTGPU_STR(SOFTGPU_MINOR), \
	SOFTGPU_STR(SOFTGPU_PATCH), \
	SOFTGPU_STR(SOFTGPU_BUILD), \
	SOFTGPU_TAG)

#define SOFTGPU_VERSION_NUM \
 	SOFTGPU_MAJOR,SOFTGPU_MINOR,SOFTGPU_PATCH,SOFTGPU_BUILD \

#endif /* __SOFTGPU_VERSION_H__INCLUDED__ */
